import AppKit

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = 0

    private let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.agilebits.onepassword"),
    ]

    private static let remoteClipboardType = NSPasteboard.PasteboardType("com.apple.is-remote-clipboard")

    var onChange: ((ClipboardItem) -> Void)?

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        if let item = readClipboard(pb) {
            onChange?(item)
        } else if isRemoteClipboard(pb) {
            // Universal Clipboard: datos no disponibles aún, reintentar
            retryRemoteClipboard()
        }
    }

    private func isRemoteClipboard(_ pb: NSPasteboard) -> Bool {
        (pb.types ?? []).contains(Self.remoteClipboardType)
    }

    private func retryRemoteClipboard() {
        let countAtSchedule = lastChangeCount
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { [weak self] in
            guard let self else { return }
            let pb = NSPasteboard.general
            // Solo reintentar si el clipboard no cambió de nuevo (evita duplicados)
            guard pb.changeCount == countAtSchedule else { return }
            if let item = self.readClipboard(pb) {
                self.onChange?(item)
            }
        }
    }

    private func readClipboard(_ pb: NSPasteboard) -> ClipboardItem? {
        let types = pb.types ?? []

        for ct in concealedTypes {
            if types.contains(ct) { return nil }
        }

        guard !types.isEmpty else { return nil }

        // Text
        if let string = pb.string(forType: .string), !string.isEmpty {
            return ClipboardItem(content: .text(string))
        }

        // Image
        if let data = pb.data(forType: .png) {
            return ClipboardItem(content: .image(data))
        }
        if let data = pb.data(forType: .tiff) {
            return ClipboardItem(content: .image(data))
        }

        return nil
    }

    static func writeToClipboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .image(let d):
            pb.setData(d, forType: .png)
        }
    }
}
