import AppKit
import Combine

final class ClipboardMonitor {
    private var timer: Timer?
    private var lastChangeCount: Int = 0

    private let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"),
        .init("com.agilebits.onepassword"),
    ]

    var onChange: ((ClipboardItem) -> Void)?

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        if let item = readClipboard(pb) {
            onChange?(item)
        }
    }

    private func readClipboard(_ pb: NSPasteboard) -> ClipboardItem? {
        let types = pb.types ?? []

        // Skip passwords, transient, auto-generated
        for ct in concealedTypes {
            if types.contains(ct) { return nil }
        }

        // Skip empty
        guard !types.isEmpty else { return nil }

        // Text
        if let string = pb.string(forType: .string), !string.isEmpty {
            return ClipboardItem(content: .text(string))
        }

        // Image
        if let data = pb.data(forType: .png) {
            return ClipboardItem(content: .image(data))
        }
        if let data = pb.data(forType: .tiff) {
            return ClipboardItem(content: .image(data))
        }

        return nil
    }

    /// Write content back to the clipboard
    static func writeToClipboard(_ item: ClipboardItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.content {
        case .text(let s):
            pb.setString(s, forType: .string)
        case .image(let d):
            pb.setData(d, forType: .png)
        }
    }
}
